const dotenv = require("dotenv");

dotenv.config();

const { MONGO_DB_DBNAME } = require("../constants.js");

const PORT = process.env.PORT;
const CORS_ORIGIN = process.env.CORS_ORIGIN;
const ADMIN_SECRET = process.env.ADMIN_SECRET;
const MONGO_DB_URL = process.env.MONGO_DB_URL;
const GITHUB_CLIENT_ID = process.env.GITHUB_CLIENT_ID;
const GITHUB_CALLBACK_URI = process.env.GITHUB_CALLBACK_URI;
const GITHUB_CLIENT_SECRET = process.env.GITHUB_CLIENT_SECRET;
const EMAIL_VERIFICATION_URL = process.env.EMAIL_VERIFICATION_URL;
const EMAIL_VERIFICATION_KEY = process.env.EMAIL_VERIFICATION_KEY;
const ACCESS_TOKEN_SECRET_STRING = process.env.ACCESS_TOKEN_SECRET_STRING;
const REFRESH_TOKEN_SECRET_STRING = process.env.REFRESH_TOKEN_SECRET_STRING;
const SESSION_TOKEN_SECRET_STRING = process.env.SESSION_TOKEN_SECRET_STRING;

module.exports = {
    PORT,
    CORS_ORIGIN,
    MONGO_DB_URL,
    ADMIN_SECRET,
    MONGO_DB_DBNAME,
    GITHUB_CLIENT_ID,
    GITHUB_CALLBACK_URI,
    GITHUB_CLIENT_SECRET,
    EMAIL_VERIFICATION_URL,
    EMAIL_VERIFICATION_KEY,
    ACCESS_TOKEN_SECRET_STRING,
    SESSION_TOKEN_SECRET_STRING,
    REFRESH_TOKEN_SECRET_STRING,
};
